name: "md-to-tex"
description: "Convert multiple markdown files into a single TeX file"
inputs:
  input-path:
    description: "Path to markdown file or directory with markdown files"
    required: true
    default: "./"
  output-path:
    description: "Path to LaTeX root directory"
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - run: npm install --prefix ${{github.action_path}}
      shell: bash
    - run: npm run build --prefix ${{github.action_path}}
      shell: bash
    - name: Compile MD to TeX
      run: npm run start --prefix ${{github.action_path}} -- -i ${{github.workspace}}/${{inputs.input-path}} -o  ${{github.workspace}}/${{inputs.output-path}}
      shell: bash
    - name: Compile TeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: ${{inputs.output-path}}
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: LaTeX & PDF
        path: ${{inputs.output-path}}
branding:
  icon: "edit"
  color: "gray-dark"
